import { drizzle } from "drizzle-orm/mysql2";
import { properties } from "../drizzle/schema.ts";

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL not set");
  process.exit(1);
}

const db = drizzle(process.env.DATABASE_URL);

const sampleProperties = [
  // ─── NAIROBI ───────────────────────────────────────────────────
  {
    title: "Modern Bedsitter in Kilimani",
    location: "Kilimani",
    city: "Nairobi",
    rentPrice: 15000,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "bedsitter",
    amenities: "WiFi, Security, Parking, Water Heater",
    description: "A cozy bedsitter in the heart of Kilimani, close to shops and public transport.",
    landlordName: "James Mwangi",
    landlordPhone: "0712345678",
    isFeatured: 1,
  },
  {
    title: "Spacious 1BR in Westlands",
    location: "Westlands",
    city: "Nairobi",
    rentPrice: 25000,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "1BR",
    amenities: "WiFi, Gym, Pool, Security, Parking, Balcony",
    description: "Modern one-bedroom apartment with city views and premium amenities in Westlands.",
    landlordName: "Sarah Odhiambo",
    landlordPhone: "0723456789",
    isFeatured: 1,
  },
  {
    title: "Elegant 2BR Apartment in Karen",
    location: "Karen",
    city: "Nairobi",
    rentPrice: 45000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "2BR",
    amenities: "Garden, Security, Parking, WiFi, Generator, Swimming Pool",
    description: "Beautiful two-bedroom apartment in a gated community with lush gardens.",
    landlordName: "Peter Kamau",
    landlordPhone: "0734567890",
    isFeatured: 1,
  },
  {
    title: "Luxury 3BR in Lavington",
    location: "Lavington",
    city: "Nairobi",
    rentPrice: 65000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "3BR",
    amenities: "Garden, Security, Parking, WiFi, Generator, Pool, Gym, Staff Quarters",
    description: "Stunning three-bedroom apartment with modern finishes in a prime location.",
    landlordName: "Grace Njeri",
    landlordPhone: "0745678901",
    isFeatured: 0,
  },
  {
    title: "Cozy Bedsitter in Eastlands",
    location: "Donholm",
    city: "Nairobi",
    rentPrice: 7000,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "bedsitter",
    amenities: "Security, Water, Parking",
    description: "Affordable bedsitter ideal for students and young professionals.",
    landlordName: "John Kiprop",
    landlordPhone: "0756789012",
    isFeatured: 0,
  },
  {
    title: "Modern Maisonette in Langata",
    location: "Langata",
    city: "Nairobi",
    rentPrice: 55000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "maisonette",
    amenities: "Garden, Security, Parking, WiFi, Generator, Staff Quarters",
    description: "Spacious maisonette with private compound and modern finishes.",
    landlordName: "Mary Wanjiku",
    landlordPhone: "0767890123",
    isFeatured: 1,
  },
  {
    title: "Studio Apartment in South B",
    location: "South B",
    city: "Nairobi",
    rentPrice: 18000,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    amenities: "WiFi, Security, Parking, Water Heater",
    description: "Well-maintained studio apartment in a secure estate.",
    landlordName: "David Omondi",
    landlordPhone: "0778901234",
    isFeatured: 0,
  },
  {
    title: "2BR Apartment in Rongai",
    location: "Rongai",
    city: "Nairobi",
    rentPrice: 15000,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "2BR",
    amenities: "Parking, Security, Water, WiFi",
    description: "Affordable two-bedroom apartment near Rongai market and schools.",
    landlordName: "Ann Muthoni",
    landlordPhone: "0789012345",
    isFeatured: 0,
  },
  {
    // ─── MOMBASA ─────────────────────────────────────────────────
    title: "Beachfront Bedsitter in Nyali",
    location: "Nyali",
    city: "Mombasa",
    rentPrice: 12000,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "bedsitter",
    amenities: "Ocean View, Security, Parking, WiFi",
    description: "Lovely bedsitter with ocean breeze in the popular Nyali area.",
    landlordName: "Ali Hassan",
    landlordPhone: "0790123456",
    isFeatured: 1,
  },
  {
    title: "1BR Apartment in Tudor",
    location: "Tudor",
    city: "Mombasa",
    rentPrice: 18000,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "1BR",
    amenities: "WiFi, Security, Parking, Water Heater, Balcony",
    description: "Comfortable one-bedroom apartment near Tudor creek.",
    landlordName: "Fatma Salim",
    landlordPhone: "0701234567",
    isFeatured: 0,
  },
  {
    title: "2BR House in Mtwapa",
    location: "Mtwapa",
    city: "Mombasa",
    rentPrice: 25000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "2BR",
    amenities: "Garden, Security, Parking, WiFi, Pool",
    description: "Spacious two-bedroom house with garden in the coastal town of Mtwapa.",
    landlordName: "Mohammed Rashid",
    landlordPhone: "0712345670",
    isFeatured: 1,
  },
  {
    title: "3BR Maisonette in Bamburi",
    location: "Bamburi",
    city: "Mombasa",
    rentPrice: 40000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "maisonette",
    amenities: "Garden, Security, Parking, WiFi, Pool, Generator",
    description: "Premium maisonette near Bamburi beach with full amenities.",
    landlordName: "Aisha Mohammed",
    landlordPhone: "0723456780",
    isFeatured: 0,
  },
  {
    title: "Studio in Changamwe",
    location: "Changamwe",
    city: "Mombasa",
    rentPrice: 8000,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "apartment",
    amenities: "Security, Parking, Water",
    description: "Affordable studio apartment ideal for singles.",
    landlordName: "Hassan Ali",
    landlordPhone: "0734567891",
    isFeatured: 0,
  },
  {
    title: "Luxury Apartment in Shanzu",
    location: "Shanzu",
    city: "Mombasa",
    rentPrice: 35000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    amenities: "Ocean View, Pool, Gym, Security, WiFi, Parking",
    description: "Beachside luxury apartment with stunning ocean views.",
    landlordName: "Zara Ibrahim",
    landlordPhone: "0745678902",
    isFeatured: 1,
  },
  // ─── KISUMU ────────────────────────────────────────────────────
  {
    title: "Bedsitter in Milimani",
    location: "Milimani",
    city: "Kisumu",
    rentPrice: 8000,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "bedsitter",
    amenities: "Security, Parking, WiFi",
    description: "Affordable bedsitter in a quiet Milimani neighborhood.",
    landlordName: "George Owino",
    landlordPhone: "0756789013",
    isFeatured: 0,
  },
  {
    title: "1BR Apartment in Obunga",
    location: "Obunga",
    city: "Kisumu",
    rentPrice: 12000,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "1BR",
    amenities: "WiFi, Security, Parking",
    description: "Well-located one-bedroom apartment near Kisumu CBD.",
    landlordName: "Mercy Akinyi",
    landlordPhone: "0767890124",
    isFeatured: 0,
  },
  {
    title: "2BR House in Kisumu West",
    location: "Kisumu West",
    city: "Kisumu",
    rentPrice: 20000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "2BR",
    amenities: "Garden, Security, Parking, WiFi",
    description: "Spacious two-bedroom house with a small garden compound.",
    landlordName: "Samuel Otieno",
    landlordPhone: "0778901235",
    isFeatured: 1,
  },
  {
    title: "3BR Apartment in Nyalenda",
    location: "Nyalenda",
    city: "Kisumu",
    rentPrice: 30000,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "3BR",
    amenities: "Security, Parking, WiFi, Water Heater, Balcony",
    description: "Large three-bedroom apartment with lake views.",
    landlordName: "Ruth Adhiambo",
    landlordPhone: "0789012346",
    isFeatured: 0,
  },
  {
    title: "Modern Apartment in Dunga",
    location: "Dunga",
    city: "Kisumu",
    rentPrice: 15000,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    amenities: "WiFi, Security, Parking, Lake View",
    description: "Modern apartment near Lake Victoria with scenic views.",
    landlordName: "Patrick Okoth",
    landlordPhone: "0790123457",
    isFeatured: 0,
  },
  // ─── NAKURU ────────────────────────────────────────────────────
  {
    title: "Bedsitter in Lanet",
    location: "Lanet",
    city: "Nakuru",
    rentPrice: 6000,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "bedsitter",
    amenities: "Security, Parking",
    description: "Budget-friendly bedsitter in a peaceful area.",
    landlordName: "Daniel Kiprono",
    landlordPhone: "0701234568",
    isFeatured: 0,
  },
  {
    title: "1BR in Milimani Nakuru",
    location: "Milimani",
    city: "Nakuru",
    rentPrice: 15000,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "1BR",
    amenities: "WiFi, Security, Parking, Water Heater",
    description: "Comfortable one-bedroom apartment near Nakuru town center.",
    landlordName: "Jane Wairimu",
    landlordPhone: "0712345671",
    isFeatured: 0,
  },
  {
    title: "2BR Apartment in Njoro",
    location: "Njoro",
    city: "Nakuru",
    rentPrice: 18000,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "2BR",
    amenities: "Security, Parking, WiFi, Garden",
    description: "Family-friendly two-bedroom apartment in Njoro town.",
    landlordName: "Paul Kibet",
    landlordPhone: "0723456781",
    isFeatured: 0,
  },
  {
    title: "3BR Maisonette in Section 58",
    location: "Section 58",
    city: "Nakuru",
    rentPrice: 35000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "maisonette",
    amenities: "Garden, Security, Parking, WiFi, Generator, Staff Quarters",
    description: "Beautiful maisonette with spacious compound in Section 58.",
    landlordName: "Catherine Chebet",
    landlordPhone: "0734567892",
    isFeatured: 1,
  },
  {
    title: "Studio in London",
    location: "London",
    city: "Nakuru",
    rentPrice: 10000,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "apartment",
    amenities: "Security, Parking, WiFi",
    description: "Modern studio apartment in a secure estate.",
    landlordName: "Eric Kiprop",
    landlordPhone: "0745678903",
    isFeatured: 0,
  },
];

console.log("Seeding database with sample properties...");

try {
  // Clear existing data
  await db.delete(properties).execute();
  console.log("Cleared existing properties");

  // Insert all properties
  for (const prop of sampleProperties) {
    await db.insert(properties).values(prop);
  }
  console.log(`Successfully seeded ${sampleProperties.length} properties`);
} catch (error) {
  console.error("Seed failed:", error);
  process.exit(1);
}
